# Generated by Django 5.2.3 on 2025-07-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trait',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
